#%RAML 1.0 NamedExample   
   "PatientName": "Sita"
   "Country": "India"
   "Gender": "Female"
   "PatientId": "0003"
   "City": "Hyderabad"
   "ContactNumber": "7894561230"
   "Hospitalvisited": "CareHospital"
   "LastvisitedDate": "12/10/2021"
   "PatientSummary": "AbdomenPain"
   "ConsultedDoctor": "Dr.Ramana"
   "Age": "45"
    

